#+TITLE:Into Starlight
#+SUBTITLE:A Starbound Mod
#+AUTHOR:Shawn Martin-Truesdell
#+EMAIL:shawn@martin-truesdell.com

Add a new progression system to your game with =Into Starlight='s passive skill tree. Customize your journey by choosing which skills matter to your playstyle.

(TODO: Add image(s) here)

#+BEGIN_QUOTE
*NOTE About Compatable Mods*: This mod is *Incompatable* with Sayter's /Frackin' Universe/ and with IcyVines' /RPG Growth/ as they introduce similar progression systems. See below for other compatability/incompatability details.
#+END_QUOTE

* Features

** Earn skill points

Killing monsters and farming plants yields *Skill Motes* which allow you to unlock additional *Skill Points*.

** Spend skill points to customize your build

Explore the *Skill Tree* by spending your points the way you want to. Your character can be as focused or diverse in their *Skills* as you choose, with each choice building on the last.

** Unlock powerful Perks

If increasing your stats is how we measure progression, Perks are the destination. Each perk requires a certain investment of skill points to reach, but unlocking it will provide you with really unique powers to help make your character your own.

* Installating the mod

** Dependencies

Install the following dependencies from the Steam Workshop or Starbound community:

- /LuaPluginLib/

** Optional Dependencies

- /StardustCore/ or /StardustLite/ will make it easier to access the UI by including the Quickbar

** Install the mod

Subscribe to the mod in the Steam Workshop or download a release =.pak= file and put it in your =/Starbound/mods= folder.

* Uninstalling the mod

1. Dispose of any of the following items:
   - Digital Starchart
   - Starchart Memory Core

2. Save and Quit naturally

3. Unsubscribe from the mod in the Steam Workshop or remove the =.pak= file from your =/Starbound/mods= folder.

* Compatability

** Multiplayer

/Into Starlight/ should work fine in multiplayer, but it IS server-side and will need to be downloaded by all players.

** Incompatable Mods

*** /RPG Growth/

/Into Starlight/ introduces *very* similar concepts to those found in RPG Growth, but does so in a very different way. As a result, these two mods might not crash your game if you combine them, but they won't play well together.

** Compatible Mods FAQ

*** Is this compatible with /Frackin' Universe/?

Actually... no. It's a bummer, but the folks over at /Frackin' Universe/ have modified/replaced some of the base asset scripts from Starbound (without hooks) to add their features and that makes it incompatable with /LuaPluginLib/... which in turn makes it incompatable with us.


*** Is this compatible with <insert species mod here>? What about /Race Traits/?

The skill tree detects your species and applies species-specific skills as an alternative/supplement to the racial traits provided by /Race Traits/ or /Frackin' Universe/.

Without configuration, custom races will use a generic start. Mod authors are encouraged to read accompanying documentation about how to integrate their mod and add a custom skill tree module.


* Special Thanks

** Omeruin's Modding Cave

The folks on the #modding-development channel over at Omeruin's have been super helpful, supportive, and at times inspirational in helping to get this mod made. Big thanks to them!

** Sayter and the /Frackin' Universe/ Team

A special note and attribution here to /Frackin' Universe/ and its creators for inspiration. The /ztarbound/ Research Tree provided by /FU/ inspired the skill tree and lent some very useful examples.

** IcyVines and /RPG Growth/

 /RPG Growth/ was an obvious source of inspiration and know-how.
