#+TITLE:Into Starlight
#+SUBTITLE:A Starbound Mod
#+AUTHOR:Shawn Martin-Truesdell
#+EMAIL:shawn@martin-truesdell.com

Add a new progression system to your game with =Into Starlight='s passive skill tree. Customize your journey by choosing which skills matter to your playstyle.

(TODO: Add image(s) here)

#+BEGIN_QUOTE
*NOTE*: This mod is *Incompatable* with IcyVines' /RPG Growth/ as they introduce similar progression systems. See below for other compatability/incompatability details.
#+END_QUOTE

* Features

** Level up your character

Killing enemies, completing quests, and farming generate =motes of experience= which contribute to your character gaining *Levels*. Each *Level* provides you with greater power and skill points which can be spent in the *Skill Tree.*

** Spend skill points to customize your build

Explore the *Skill Tree* by spending your points the way you want to. Your character can be as focused or diverse in their *Skills* as you choose, with each choice building on the last.

* Installating the Mod

Subscribe to the mod in the Steam Workshop or download a release =.pak= file and put it in your =/Starbound/mods= folder.

* Uninstalling the Mod

#+BEGIN_QUOTE
As of this time there are no "Mod Specific Items" to manage. This might change, but for the time being uninstalling the mod should be trivial.
#+END_QUOTE

Unsubscribe from the mod in the Steam Workshop or remove the =.pak= file from your =/Starbound/mods= folder.

* Compatability

** Incompatable Mods

*** /RPG Growth/

/Into Starlight/ introduces *very* similar concepts to those found in RPG Growth, but does so in a very different way. As a result, these two mods might not crash your game if you combine them, but they won't play well together.

** Compatible Mods FAQ

*** Is this compatible with /Frackin' Universe/?

Should be! A lot of our testing is done with /Frackin' Universe/ loaded. With that said, Sayter would tell you that any mod that changes player progression will upset /FU/'s balance and will likely make the player super over-powered relative to the game's challenges. Consider beating /Frackin' Universe/ without /Into Starlight/ first to see it in all its glory.

*** Is this compatible with <insert species mod here>?

The skill tree detects your species and applies species-specific skills as an alternative/supplement to the racial traits provided by /Race Traits/ or /Frackin' Universe/.

Without configuration, custom races will use a generic start. Mod authors are encouraged to read accompanying documentation about how to integrate their mod and add a custom skill tree module.

* Special Thanks

** Sayter and /Frackin' Universe/

A special note and attribution here to /Frackin' Universe/ and its creator for inspiration. The Research Tree provided by /FU/ proved the viability of the skill tree and lent some very useful examples.

** IcyVines and /RPG Growth/

While it is incompatable, /RPG Growth/ was an obvious source of inspiration and know-how.
